@extends('admin.layouts.app')
@section('content')
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
    <div><div class="eyebrow">{{ app()->getLocale() === 'ar' ? 'الاشتراكات' : 'Subscriptions' }}</div><h1 class="page-title mb-1">{{ app()->getLocale() === 'ar' ? 'الباقات والأسعار' : 'Packages and pricing' }}</h1><p class="text-secondary mb-0">{{ app()->getLocale() === 'ar' ? 'إدارة الباقات التي تظهر لمالكي الصيدليات.' : 'Manage packages shown to pharmacy owners.' }}</p></div>
</div>
<div class="row g-4">
    <div class="col-xl-4"><div class="card p-4"><h2 class="h5">{{ app()->getLocale() === 'ar' ? 'إضافة باقة' : 'Add package' }}</h2><form method="POST" action="{{ route('admin.packages.store') }}">@csrf<input class="form-control mb-2" name="name" placeholder="{{ app()->getLocale() === 'ar' ? 'اسم الباقة' : 'Package name' }}" required><input class="form-control mb-2" name="price" type="number" step=".01" placeholder="{{ app()->getLocale() === 'ar' ? 'السعر' : 'Price' }}" required><input class="form-control mb-2" name="duration_in_days" type="number" min="1" placeholder="{{ app()->getLocale() === 'ar' ? 'المدة بالأيام' : 'Duration in days' }}" required><textarea class="form-control mb-3" name="description" placeholder="{{ app()->getLocale() === 'ar' ? 'المميزات: اكتب كل ميزة في سطر مستقل' : 'Features: write one feature per line' }}"></textarea><button class="btn btn-primary w-100">{{ app()->getLocale() === 'ar' ? 'إنشاء الباقة' : 'Create package' }}</button></form></div></div>
    <div class="col-xl-8"><div class="card p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th>{{ app()->getLocale() === 'ar' ? 'الباقة' : 'Name' }}</th><th>{{ app()->getLocale() === 'ar' ? 'السعر' : 'Price' }}</th><th>{{ app()->getLocale() === 'ar' ? 'المدة' : 'Duration' }}</th><th>{{ app()->getLocale() === 'ar' ? 'الحالة' : 'Status' }}</th><th>{{ app()->getLocale() === 'ar' ? 'الإجراءات' : 'Actions' }}</th></tr></thead><tbody>@forelse($packages as $package)<tr><td class="fw-semibold">{{ $package->name }}<div class="small text-secondary">{{ $package->description }}</div></td><td>${{ number_format($package->price, 2) }}</td><td>{{ $package->duration_in_days }} {{ app()->getLocale() === 'ar' ? 'يوم' : 'days' }}</td><td><span class="badge {{ $package->is_active ? 'badge-open' : 'badge-closed' }}">{{ $package->is_active ? (app()->getLocale() === 'ar' ? 'نشطة' : 'Active') : (app()->getLocale() === 'ar' ? 'متوقفة' : 'Inactive') }}</span></td><td class="text-nowrap"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editPackage{{ $package->id }}">{{ app()->getLocale() === 'ar' ? 'تعديل الباقة' : 'Edit package' }}</button> <form class="d-inline" method="POST" action="{{ route('admin.packages.status', $package) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-warning">{{ $package->is_active ? (app()->getLocale() === 'ar' ? 'إيقاف' : 'Disable') : (app()->getLocale() === 'ar' ? 'تفعيل' : 'Enable') }}</button></form><form class="d-inline" method="POST" action="{{ route('admin.packages.destroy', $package) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr>@empty<tr><td colspan="5" class="text-center text-secondary py-4">{{ app()->getLocale() === 'ar' ? 'لا توجد باقات.' : 'No packages found.' }}</td></tr>@endforelse</tbody></table></div></div></div>
</div>
@foreach($packages as $package)
<div class="modal fade" id="editPackage{{ $package->id }}" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="{{ route('admin.packages.update', $package) }}">@csrf @method('PATCH')<div class="modal-header"><h5 class="modal-title">{{ app()->getLocale() === 'ar' ? 'تعديل الباقة والسعر والمميزات' : 'Edit package, price and features' }}</h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input class="form-control mb-2" name="name" value="{{ $package->name }}" required><input class="form-control mb-2" name="price" type="number" step=".01" value="{{ $package->price }}" required><input class="form-control mb-2" name="duration_in_days" type="number" min="1" value="{{ $package->duration_in_days }}" required><label class="form-label">{{ app()->getLocale() === 'ar' ? 'مميزات العرض' : 'Offer features' }}</label><textarea class="form-control" name="description" placeholder="{{ app()->getLocale() === 'ar' ? 'اكتب كل ميزة في سطر مستقل' : 'Write one feature per line' }}">{{ $package->description }}</textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal">{{ app()->getLocale() === 'ar' ? 'إلغاء' : 'Cancel' }}</button><button class="btn btn-primary">{{ app()->getLocale() === 'ar' ? 'حفظ التعديل' : 'Save changes' }}</button></div></form></div></div></div>
@endforeach
@endsection
