
<?php $__env->startSection('content'); ?>
<?php use Illuminate\Support\Str; ?>
<?php use Illuminate\Support\Facades\Auth; ?>
<div class="mb-4"><div class="eyebrow"><?php echo e(__('admin.management')); ?></div><h1 class="page-title mb-1"><?php echo e(__($title)); ?></h1><p class="text-secondary mb-0"><?php echo e(__($description)); ?></p></div>
<?php if($section === 'settings'): ?>
<div class="card p-4"><form method="POST" action="<?php echo e(route('admin.settings.update')); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PUT'); ?><div class="row g-3"><div class="col-md-4"><label class="form-label">Application name</label><input class="form-control" name="app_name" value="<?php echo e(old('app_name', $settings->app_name)); ?>" required></div><div class="col-md-4"><label class="form-label">Contact email</label><input class="form-control" type="email" name="contact_email" value="<?php echo e(old('contact_email', $settings->contact_email)); ?>"></div><div class="col-md-4"><label class="form-label">Contact phone</label><input class="form-control" name="contact_phone" value="<?php echo e(old('contact_phone', $settings->contact_phone)); ?>"></div><div class="col-12"><label class="form-label">Contact address</label><textarea class="form-control" name="contact_address" rows="2"><?php echo e(old('contact_address', $settings->contact_address)); ?></textarea></div><div class="col-12"><label class="form-label">Privacy policy</label><textarea class="form-control" name="privacy_policy" rows="7"><?php echo e(old('privacy_policy', $settings->privacy_policy)); ?></textarea></div><div class="col-12"><label class="form-label">Terms &amp; conditions</label><textarea class="form-control" name="terms_conditions" rows="7"><?php echo e(old('terms_conditions', $settings->terms_conditions)); ?></textarea></div></div><button class="btn btn-primary mt-4"><i class="bi bi-check2 me-1"></i>Save application settings</button></form></div>
<?php elseif($section === 'pharmacies'): ?>
<div class="card p-4"><form class="row g-2 mb-3"><div class="col-md-4"><select class="form-select" name="status"><option value="">All statuses</option><?php $__currentLoopData = ['pending','open','rejected','closed']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($status); ?>" <?php if(request('status') === $status): echo 'selected'; endif; ?>><?php echo e(ucfirst($status)); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-auto"><button class="btn btn-outline-secondary">Filter</button></div></form><div class="table-responsive"><table class="table"><thead><tr><th>Pharmacy</th><th>Owner</th><th>Contact</th><th>License</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><strong><?php echo e($item->name); ?></strong><div class="small text-secondary"><?php echo e(Str::limit($item->address, 38)); ?></div></td><td><?php echo e($item->user?->name); ?><div class="small text-secondary"><?php echo e($item->user?->email); ?></div></td><td><?php echo e($item->phone ?: '—'); ?></td><td><?php echo e($item->license_number ?: '—'); ?></td><td><span class="badge badge-<?php echo e($item->status); ?>"><?php echo e(ucfirst($item->status)); ?></span></td><td class="text-end text-nowrap"><?php if($item->status === 'pending'): ?><form class="d-inline" method="POST" action="<?php echo e(route('admin.pharmacies.approve',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-sm btn-success" title="Approve"><i class="bi bi-check2"></i></button></form> <form class="d-inline" method="POST" action="<?php echo e(route('admin.pharmacies.request-info',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-sm btn-outline-primary" title="Request additional information"><i class="bi bi-chat-square-text"></i></button></form> <form class="d-inline" method="POST" action="<?php echo e(route('admin.pharmacies.reject',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-sm btn-outline-danger" title="Reject"><i class="bi bi-x-lg"></i></button></form><?php else: ?><span class="small text-secondary">Reviewed</span><?php endif; ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="6" class="text-center text-secondary py-4">No pharmacies match this filter.</td></tr><?php endif; ?></tbody></table></div><?php echo e($items->withQueryString()->links()); ?></div>
<?php elseif($section === 'users'): ?>
<div class="row g-4">
	<div class="col-xl-4">
		<div class="card p-4">
			<h2 class="h5"><?php echo e(isset($editUser) ? __('admin.edit_user') : __('admin.add_user')); ?></h2>
			<form method="POST" action="<?php echo e(isset($editUser) ? route('admin.users.update', $editUser) : route('admin.users.store')); ?>">
				<?php echo csrf_field(); ?>
				<?php if(isset($editUser)): ?> <?php echo method_field('PATCH'); ?> <?php endif; ?>
				<input class="form-control mb-2" name="name" placeholder="<?php echo e(__('admin.full_name')); ?>" value="<?php echo e(old('name', $editUser->name ?? '')); ?>" required>
				<input class="form-control mb-2" type="email" name="email" placeholder="<?php echo e(__('admin.email')); ?>" value="<?php echo e(old('email', $editUser->email ?? '')); ?>" required>
				<?php if(!isset($editUser)): ?>
					<input class="form-control mb-2" type="password" name="password" placeholder="<?php echo e(__('admin.temporary_password')); ?>" required>
				<?php else: ?>
					<input class="form-control mb-2" type="password" name="password" placeholder="<?php echo e(__('admin.new_password')); ?>">
				<?php endif; ?>
				<select class="form-select mb-3" name="role">
					<option value="admin" <?php if(old('role', $editUser->role ?? '')==='admin'): echo 'selected'; endif; ?>><?php echo e(__('admin.administrator')); ?></option>
					<option value="manager" <?php if(old('role', $editUser->role ?? '')==='manager'): echo 'selected'; endif; ?>><?php echo e(__('admin.manager')); ?></option>
				</select>
				<button class="btn btn-primary w-100"><?php echo e(isset($editUser) ? __('admin.save_changes') : __('admin.create_user')); ?></button>
				<?php if(isset($editUser)): ?><a href="<?php echo e(route('admin.users')); ?>" class="btn btn-link mt-2"><?php echo e(__('admin.cancel')); ?></a><?php endif; ?>
			</form>
		</div>
	</div>
	<div class="col-xl-8">
		<div class="card p-4 mb-3">
			<form class="row g-2" method="GET" action="<?php echo e(route('admin.users')); ?>">
				<div class="col">
					<input class="form-control" name="q" placeholder="<?php echo e(__('admin.search_name_email')); ?>" value="<?php echo e($search ?? ''); ?>">
				</div>
				<div class="col-auto"><button class="btn btn-outline-secondary"><?php echo e(__('admin.search')); ?></button></div>
			</form>
		</div>
		<div class="card p-4">
			<div class="table-responsive">
				<table class="table">
					<thead><tr><th><?php echo e(__('admin.name')); ?></th><th><?php echo e(__('admin.email')); ?></th><th><?php echo e(__('admin.role')); ?></th><th><?php echo e(__('admin.joined')); ?></th><th></th></tr></thead>
					<tbody>
						<?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
							<tr>
								<td class="fw-semibold"><?php echo e($item->name); ?></td>
								<td><?php echo e($item->email); ?></td>
								<td><span class="badge bg-light text-dark"><?php echo e(str_replace('_',' ',ucfirst($item->role))); ?></span></td>
								<td><?php echo e($item->created_at->format('d M Y')); ?></td>
								<td class="text-end">
									<?php if(!$item->is(Auth::user())): ?>
										<a href="<?php echo e(route('admin.users.edit', $item)); ?>" class="btn btn-sm btn-outline-primary me-2"><i class="bi bi-pencil"></i></a>
										<form class="d-inline" method="POST" action="<?php echo e(route('admin.users.destroy',$item)); ?>">
											<?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?>
											<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button>
										</form>
									<?php endif; ?>
								</td>
							</tr>
						<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
					</tbody>
				</table>
			</div>
			<?php echo e($items->links()); ?>

		</div>
	</div>
</div>
<?php elseif($section === 'app-users'): ?>
<div class="row g-4">
	<div class="col-xl-4"><div class="card p-4"><h2 class="h5"><?php echo e(__('admin.add_app_user')); ?></h2><form method="POST" action="<?php echo e(route('admin.app-users.store')); ?>"><?php echo csrf_field(); ?><input class="form-control mb-2" name="name" placeholder="<?php echo e(__('admin.full_name')); ?>" required><input class="form-control mb-2" type="email" name="email" placeholder="<?php echo e(__('admin.email')); ?>" required><input class="form-control mb-2" name="phone" placeholder="<?php echo e(__('admin.phone')); ?>"><input class="form-control mb-2" type="password" name="password" placeholder="<?php echo e(__('admin.temporary_password')); ?>" required><select class="form-select mb-3" name="role"><option value="customer"><?php echo e(__('admin.customer')); ?></option><option value="pharmacy_owner"><?php echo e(__('admin.pharmacy_owner')); ?></option></select><button class="btn btn-primary w-100"><?php echo e(__('admin.create_user')); ?></button></form></div></div>
	<div class="col-xl-8"><div class="card p-4 mb-3"><form class="row g-2" method="GET" action="<?php echo e(route('admin.app-users')); ?>"><div class="col"><input class="form-control" name="q" placeholder="<?php echo e(__('admin.search_name_email')); ?>" value="<?php echo e($search ?? ''); ?>"></div><div class="col-auto"><button class="btn btn-outline-secondary"><?php echo e(__('admin.search')); ?></button></div></form></div><div class="card p-4"><div class="table-responsive"><table class="table"><thead><tr><th><?php echo e(__('admin.name')); ?></th><th><?php echo e(__('admin.email')); ?></th><th><?php echo e(__('admin.role')); ?></th><th><?php echo e(__('admin.status')); ?></th><th><?php echo e(__('admin.actions')); ?></th></tr></thead><tbody><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="fw-semibold"><?php echo e($item->name); ?><div class="small text-secondary"><?php echo e($item->phone ?: '—'); ?></div></td><td><?php echo e($item->email); ?></td><td><?php echo e($item->role === 'pharmacy_owner' ? __('admin.pharmacy_owner') : __('admin.customer')); ?></td><td><span class="badge <?php echo e($item->is_active ? 'badge-open' : 'badge-closed'); ?>"><?php echo e($item->is_active ? __('admin.active') : __('admin.inactive')); ?></span></td><td class="text-nowrap"><form class="d-inline" method="POST" action="<?php echo e(route('admin.app-users.status', $item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-sm btn-outline-warning"><?php echo e($item->is_active ? __('admin.deactivate') : __('admin.activate')); ?></button></form> <form class="d-inline" method="POST" action="<?php echo e(route('admin.app-users.destroy', $item)); ?>" onsubmit="return confirm('<?php echo e(__('admin.delete_app_user_confirm')); ?>')"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div><?php echo e($items->links()); ?></div></div>
</div>
<?php elseif($section === 'categories'): ?>
<div class="row g-4"><div class="col-lg-4"><div class="card p-4"><h2 class="h5">New category</h2><form method="POST" action="<?php echo e(route('admin.categories.store')); ?>"><?php echo csrf_field(); ?><input class="form-control mb-2" name="name" placeholder="Category name" required><textarea class="form-control mb-3" name="description" rows="3" placeholder="Description"></textarea><button class="btn btn-primary">Add category</button></form></div></div><div class="col-lg-8"><div class="card p-4"><table class="table"><thead><tr><th>Name</th><th>Description</th><th>Medicines</th><th></th></tr></thead><tbody><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="fw-semibold"><?php echo e($item->name); ?></td><td><?php echo e(Str::limit($item->description,55)); ?></td><td><?php echo e($item->medicines_count); ?></td><td class="text-end"><form method="POST" action="<?php echo e(route('admin.categories.destroy',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table><?php echo e($items->links()); ?></div></div></div>
<?php elseif($section === 'medicines'): ?>
<div class="card p-4 mb-4"><h2 class="h5">Add medicine</h2><form method="POST" action="<?php echo e(route('admin.medicines.store')); ?>"><?php echo csrf_field(); ?><div class="row g-2"><div class="col-md-3"><input class="form-control" name="name" placeholder="Medicine name" required></div><div class="col-md-2"><select class="form-select" name="category_id" required><option value="">Category</option><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category->id); ?>"><?php echo e($category->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-2"><input class="form-control" name="price" type="number" step=".01" placeholder="Price" required></div><div class="col-md-2"><input class="form-control" name="quantity" type="number" placeholder="Quantity" required></div><div class="col-md-2"><input class="form-control" name="discount_percentage" type="number" placeholder="Discount %" required></div><div class="col-md-1"><button class="btn btn-primary w-100" title="Add medicine"><i class="bi bi-plus-lg"></i></button></div></div></form></div><div class="card p-4"><div class="table-responsive"><table class="table"><thead><tr><th>Medicine</th><th>Category</th><th>Price</th><th>Stock</th><th>Available</th><th></th></tr></thead><tbody><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="fw-semibold"><?php echo e($item->name); ?></td><td><?php echo e($item->category?->name); ?></td><td>$<?php echo e(number_format($item->price,2)); ?></td><td><?php echo e($item->quantity); ?></td><td><span class="badge <?php echo e($item->is_available ? 'badge-open' : 'badge-closed'); ?>"><?php echo e($item->is_available ? 'Yes' : 'No'); ?></span></td><td class="text-end"><form method="POST" action="<?php echo e(route('admin.medicines.destroy',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div><?php echo e($items->links()); ?></div>
<?php elseif($section === 'offers'): ?>
<div class="card p-4 mb-4"><h2 class="h5">Publish offer</h2><form method="POST" action="<?php echo e(route('admin.offers.store')); ?>"><?php echo csrf_field(); ?><div class="row g-2"><div class="col-md-3"><input class="form-control" name="title" placeholder="Offer title" required></div><div class="col-md-3"><select class="form-select" name="pharmacy_id" required><option value="">Pharmacy</option><?php $__currentLoopData = $pharmacies; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $pharmacy): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($pharmacy->id); ?>"><?php echo e($pharmacy->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div><div class="col-md-2"><input class="form-control" name="discount_percentage" type="number" placeholder="Discount %" required></div><div class="col-md-2"><input class="form-control" name="start_date" type="date" required></div><div class="col-md-2"><input class="form-control" name="end_date" type="date" required></div></div><button class="btn btn-primary mt-3">Publish offer</button></form></div><div class="card p-4"><table class="table"><thead><tr><th>Offer</th><th>Pharmacy</th><th>Discount</th><th>Dates</th><th></th></tr></thead><tbody><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="fw-semibold"><?php echo e($item->title); ?></td><td><?php echo e($item->pharmacy?->name); ?></td><td><?php echo e($item->discount_percentage); ?>%</td><td><?php echo e($item->start_date); ?> to <?php echo e($item->end_date); ?></td><td class="text-end"><form method="POST" action="<?php echo e(route('admin.offers.destroy',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table><?php echo e($items->links()); ?></div>
<?php elseif($section === 'orders'): ?>
<div class="card p-4"><div class="table-responsive"><table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Pharmacy</th><th>Total</th><th>Status</th><th>Update</th></tr></thead><tbody><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="fw-semibold">#<?php echo e($item->id); ?></td><td><?php echo e($item->user?->name); ?></td><td><?php echo e($item->pharmacy?->name); ?></td><td>$<?php echo e(number_format($item->total_price,2)); ?></td><td><span class="badge bg-light text-dark"><?php echo e(ucfirst($item->status)); ?></span></td><td><form class="d-flex gap-2" method="POST" action="<?php echo e(route('admin.orders.status',$item)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><select class="form-select form-select-sm" name="status"><?php $__currentLoopData = ['pending','accepted','rejected','preparing','ready','delivered','cancelled']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $status): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option <?php if($item->status === $status): echo 'selected'; endif; ?>><?php echo e($status); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select><button class="btn btn-sm btn-primary"><i class="bi bi-check2"></i></button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div><?php echo e($items->links()); ?></div>
<?php elseif(in_array($section, ['notifications','activity-logs'])): ?>
<div class="card p-4"><div class="table-responsive"><table class="table"><thead><tr><th>Type</th><th>User</th><th>Pharmacy</th><th>Details</th><th>Created</th></tr></thead><tbody><?php $__currentLoopData = $items; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><tr><td class="fw-semibold"><?php echo e(str_replace('.', ' / ', ucfirst($item->type))); ?></td><td><?php echo e($item->user?->name ?: $item->dashboardUser?->name ?: 'System'); ?></td><td><?php echo e($item->pharmacy?->name ?: '—'); ?></td><td><?php echo e(data_get(json_decode($item->data, true), 'message', Str::limit($item->data, 70))); ?></td><td><?php echo e($item->created_at->format('d M Y, H:i')); ?></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></tbody></table></div><?php echo e($items->links()); ?></div>
<?php endif; ?>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Lenovo\Desktop\Smart Pharmacy System\resources\views\admin\resource.blade.php ENDPATH**/ ?>