<?php ($editing = $item !== null); ?>
<div class="row g-3">
    <div class="col-md-6"><label class="form-label"><?php echo e(__('admin.medicine_name')); ?> <span class="text-danger">*</span></label><input class="form-control" name="name" value="<?php echo e(old('name', $item?->name)); ?>" required></div>
    <div class="col-md-6"><label class="form-label"><?php echo e(__('admin.generic_name')); ?></label><input class="form-control" name="generic_name" value="<?php echo e(old('generic_name', $item?->generic_name)); ?>"></div>
    <div class="col-md-6"><label class="form-label">Category <span class="text-danger">*</span></label><select class="form-select" name="category_id" required><option value="">Choose category</option><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($category->id); ?>" <?php if((string) old('category_id', $item?->category_id) === (string) $category->id): echo 'selected'; endif; ?>><?php echo e($category->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></select></div>
    <div class="col-md-6"><label class="form-label">Manufacturer</label><input class="form-control" name="manufacturer" value="<?php echo e(old('manufacturer', $item?->manufacturer)); ?>"></div>
    <div class="col-md-6"><label class="form-label">Dosage form</label><input class="form-control" name="dosage_form" placeholder="Tablet, syrup, cream..." value="<?php echo e(old('dosage_form', $item?->dosage_form)); ?>"></div>
    <div class="col-md-6"><label class="form-label">Strength</label><input class="form-control" name="strength" placeholder="500mg" value="<?php echo e(old('strength', $item?->strength)); ?>"></div>
    <div class="col-md-6"><label class="form-label">Barcode</label><input class="form-control" name="barcode" value="<?php echo e(old('barcode', $item?->barcode)); ?>"></div>
    <div class="col-md-6"><label class="form-label">Medicine image</label><input class="form-control" type="file" name="image" accept="image/jpeg,image/png,image/gif,image/webp"><?php if($item?->image_path): ?><div class="small text-secondary mt-1">Existing image will be kept unless replaced.</div><?php endif; ?></div>
    <div class="col-12"><label class="form-label">Description</label><textarea class="form-control" name="description" rows="3"><?php echo e(old('description', $item?->description)); ?></textarea></div>
    <div class="col-12"><div class="form-check form-switch"><input class="form-check-input" type="checkbox" name="requires_prescription" value="1" <?php if(old('requires_prescription', $item?->requires_prescription)): echo 'checked'; endif; ?>><label class="form-check-label">Requires prescription</label></div><div class="form-check form-switch mt-2"><input class="form-check-input" type="checkbox" name="is_available" value="1" <?php if(old('is_available', $item?->is_available ?? true)): echo 'checked'; endif; ?>><label class="form-check-label">Active catalog template</label></div></div>
</div>
<?php /**PATH C:\Users\Lenovo\Desktop\Smart Pharmacy System\resources\views\admin\partials\catalog-medicine-fields.blade.php ENDPATH**/ ?>