
<?php $__env->startSection('content'); ?>
<div class="d-flex flex-wrap justify-content-between align-items-end gap-3 mb-4">
    <div><div class="eyebrow"><?php echo e(app()->getLocale() === 'ar' ? 'الاشتراكات' : 'Subscriptions'); ?></div><h1 class="page-title mb-1"><?php echo e(app()->getLocale() === 'ar' ? 'الباقات والأسعار' : 'Packages and pricing'); ?></h1><p class="text-secondary mb-0"><?php echo e(app()->getLocale() === 'ar' ? 'إدارة الباقات التي تظهر لمالكي الصيدليات.' : 'Manage packages shown to pharmacy owners.'); ?></p></div>
</div>
<div class="row g-4">
    <div class="col-xl-4"><div class="card p-4"><h2 class="h5"><?php echo e(app()->getLocale() === 'ar' ? 'إضافة باقة' : 'Add package'); ?></h2><form method="POST" action="<?php echo e(route('admin.packages.store')); ?>"><?php echo csrf_field(); ?><input class="form-control mb-2" name="name" placeholder="<?php echo e(app()->getLocale() === 'ar' ? 'اسم الباقة' : 'Package name'); ?>" required><input class="form-control mb-2" name="price" type="number" step=".01" placeholder="<?php echo e(app()->getLocale() === 'ar' ? 'السعر' : 'Price'); ?>" required><input class="form-control mb-2" name="duration_in_days" type="number" min="1" placeholder="<?php echo e(app()->getLocale() === 'ar' ? 'المدة بالأيام' : 'Duration in days'); ?>" required><textarea class="form-control mb-3" name="description" placeholder="<?php echo e(app()->getLocale() === 'ar' ? 'المميزات: اكتب كل ميزة في سطر مستقل' : 'Features: write one feature per line'); ?>"></textarea><button class="btn btn-primary w-100"><?php echo e(app()->getLocale() === 'ar' ? 'إنشاء الباقة' : 'Create package'); ?></button></form></div></div>
    <div class="col-xl-8"><div class="card p-4"><div class="table-responsive"><table class="table align-middle"><thead><tr><th><?php echo e(app()->getLocale() === 'ar' ? 'الباقة' : 'Name'); ?></th><th><?php echo e(app()->getLocale() === 'ar' ? 'السعر' : 'Price'); ?></th><th><?php echo e(app()->getLocale() === 'ar' ? 'المدة' : 'Duration'); ?></th><th><?php echo e(app()->getLocale() === 'ar' ? 'الحالة' : 'Status'); ?></th><th><?php echo e(app()->getLocale() === 'ar' ? 'الإجراءات' : 'Actions'); ?></th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $packages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $package): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td class="fw-semibold"><?php echo e($package->name); ?><div class="small text-secondary"><?php echo e($package->description); ?></div></td><td>$<?php echo e(number_format($package->price, 2)); ?></td><td><?php echo e($package->duration_in_days); ?> <?php echo e(app()->getLocale() === 'ar' ? 'يوم' : 'days'); ?></td><td><span class="badge <?php echo e($package->is_active ? 'badge-open' : 'badge-closed'); ?>"><?php echo e($package->is_active ? (app()->getLocale() === 'ar' ? 'نشطة' : 'Active') : (app()->getLocale() === 'ar' ? 'متوقفة' : 'Inactive')); ?></span></td><td class="text-nowrap"><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#editPackage<?php echo e($package->id); ?>"><?php echo e(app()->getLocale() === 'ar' ? 'تعديل الباقة' : 'Edit package'); ?></button> <form class="d-inline" method="POST" action="<?php echo e(route('admin.packages.status', $package)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><button class="btn btn-sm btn-outline-warning"><?php echo e($package->is_active ? (app()->getLocale() === 'ar' ? 'إيقاف' : 'Disable') : (app()->getLocale() === 'ar' ? 'تفعيل' : 'Enable')); ?></button></form><form class="d-inline" method="POST" action="<?php echo e(route('admin.packages.destroy', $package)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('DELETE'); ?><button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="5" class="text-center text-secondary py-4"><?php echo e(app()->getLocale() === 'ar' ? 'لا توجد باقات.' : 'No packages found.'); ?></td></tr><?php endif; ?></tbody></table></div></div></div>
</div>
<?php $__currentLoopData = $packages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $package): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
<div class="modal fade" id="editPackage<?php echo e($package->id); ?>" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><form method="POST" action="<?php echo e(route('admin.packages.update', $package)); ?>"><?php echo csrf_field(); ?> <?php echo method_field('PATCH'); ?><div class="modal-header"><h5 class="modal-title"><?php echo e(app()->getLocale() === 'ar' ? 'تعديل الباقة والسعر والمميزات' : 'Edit package, price and features'); ?></h5><button type="button" class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><input class="form-control mb-2" name="name" value="<?php echo e($package->name); ?>" required><input class="form-control mb-2" name="price" type="number" step=".01" value="<?php echo e($package->price); ?>" required><input class="form-control mb-2" name="duration_in_days" type="number" min="1" value="<?php echo e($package->duration_in_days); ?>" required><label class="form-label"><?php echo e(app()->getLocale() === 'ar' ? 'مميزات العرض' : 'Offer features'); ?></label><textarea class="form-control" name="description" placeholder="<?php echo e(app()->getLocale() === 'ar' ? 'اكتب كل ميزة في سطر مستقل' : 'Write one feature per line'); ?>"><?php echo e($package->description); ?></textarea></div><div class="modal-footer"><button type="button" class="btn btn-light" data-bs-dismiss="modal"><?php echo e(app()->getLocale() === 'ar' ? 'إلغاء' : 'Cancel'); ?></button><button class="btn btn-primary"><?php echo e(app()->getLocale() === 'ar' ? 'حفظ التعديل' : 'Save changes'); ?></button></div></form></div></div></div>
<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH C:\Users\Lenovo\Desktop\Smart Pharmacy System\resources\views\admin\packages.blade.php ENDPATH**/ ?>