<!doctype html>
<html lang="{{ app()->getLocale() }}" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title ?? 'Admin dashboard' }} | Smart Pharmacy</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <style>
        :root{--ink:#17252b;--muted:#718087;--teal:#0d7773;--mint:#e8f5f0;--line:#dce7e4;--canvas:#f5f8f7}
        body{background:var(--canvas);color:var(--ink);font-family:Inter,ui-sans-serif,system-ui,sans-serif;overflow-x:hidden}.sidebar{background:#143c3b;min-height:100vh;width:250px;position:fixed;z-index:4;box-sizing:border-box}.brand{color:#fff;font-size:1.2rem;font-weight:700;letter-spacing:-.02em}.brand-mark{background:#f6c453;color:#143c3b;width:34px;height:34px;display:inline-grid;place-items:center;border-radius:10px}.nav-link{color:#b9d4cf;border-radius:8px;margin:.18rem 0;padding:.68rem .8rem}.nav-link:hover,.nav-link.active{background:#245b57;color:#fff}.main{margin-left:250px}.topbar{background:#fff;border-bottom:1px solid var(--line);height:76px}.eyebrow{color:var(--teal);font-size:.72rem;font-weight:700;letter-spacing:.11em;text-transform:uppercase}.page-title{font-size:1.75rem;font-weight:700;letter-spacing:-.04em}.card{border:1px solid var(--line);border-radius:12px;box-shadow:0 5px 18px rgba(20,60,59,.035)}.stat{border-left:4px solid var(--teal)}.stat-value{font-size:1.7rem;font-weight:750}.btn-primary{background:var(--teal);border-color:var(--teal)}.btn-primary:hover{background:#095b58;border-color:#095b58}.table{--bs-table-bg:transparent}.table th{color:var(--muted);font-size:.72rem;letter-spacing:.08em;text-transform:uppercase;font-weight:700;white-space:nowrap}.table td{vertical-align:middle}.badge{font-weight:600}.badge-pending{background:#fff1cf;color:#8a6200}.badge-open{background:#d9f4e8;color:#08734f}.badge-rejected{background:#fde1e1;color:#a12b2b}.badge-closed{background:#e9eef0;color:#5f6c71}.mobile-menu{display:none}@media(max-width:991px){.sidebar{width:100%;min-height:auto;position:relative}.main{margin-left:0}.desktop-nav{display:none}.mobile-menu{display:block}.sidebar-inner{display:flex;justify-content:space-between;align-items:center}.sidebar .collapse.show{display:block}.nav-list{display:flex;flex-wrap:wrap;gap:.25rem}.nav-link{margin:0}.topbar{height:auto}.page-title{font-size:1.4rem}}
        [dir="rtl"] body{font-family:Tahoma,Arial,sans-serif}[dir="rtl"] .main{margin-left:0;margin-right:250px}[dir="rtl"] .stat{border-left:0;border-right:4px solid var(--teal)}[dir="rtl"] .me-1{margin-right:0!important;margin-left:.25rem!important}[dir="rtl"] .me-2{margin-right:0!important;margin-left:.5rem!important}@media(max-width:991px){[dir="rtl"] .main{margin-right:0}}
    </style>
</head>
<body>
<aside class="sidebar p-3">
    <div class="sidebar-inner"><a class="brand text-decoration-none" href="{{ route('admin.dashboard') }}"><span class="brand-mark me-2"><i class="bi bi-capsule"></i></span>{{ __('admin.brand') }}</a><button class="btn btn-sm text-white mobile-menu" data-bs-toggle="collapse" data-bs-target="#adminNav"><i class="bi bi-list fs-4"></i></button></div>
    <div class="collapse show mt-4" id="adminNav"><div class="desktop-nav eyebrow text-white-50 mb-2">{{ __('admin.operations') }}</div><nav class="nav-list flex-column">
        @foreach([['dashboard','overview','speedometer2','dashboard'],['pharmacies','pharmacy_requests','hospital','pharmacies'],['app-users','app_users','people','app-users'],['users','users','person-badge','users'],['categories','categories','grid','categories'],['locations','locations','globe2','locations'],['medicine-catalog','medicine_catalog','capsule','medicine-catalog'],['packages','packages','cash-stack','packages'],['offers','offers','tag','offers'],['orders','orders','receipt','orders'],['notifications','notifications','bell','notifications'],['activity-logs','activity_logs','clock-history','activity-logs'],['settings','settings','sliders','settings']] as [$route,$label,$icon,$routeName])
            <a class="nav-link {{ ($section ?? '') === $route ? 'active' : '' }}" href="{{ route('admin.'.$routeName) }}"><i class="bi bi-{{ $icon }} me-2"></i>{{ __('admin.'.$label) }}</a>
        @endforeach
    </nav></div>
</aside>
<main class="main"><header class="topbar px-4 d-flex align-items-center justify-content-between"><div><span class="eyebrow">{{ __('admin.control_centre') }}</span><div class="small text-secondary">{{ now()->format('l, d F Y') }}</div></div><div class="d-flex align-items-center gap-2"><form method="POST" action="{{ route('admin.language') }}">@csrf<input type="hidden" name="locale" value="{{ app()->getLocale() === 'ar' ? 'en' : 'ar' }}"><button class="btn btn-sm btn-outline-secondary"><i class="bi bi-translate me-1"></i>{{ __('admin.language') }}</button></form><form method="POST" action="{{ route('admin.logout') }}">@csrf<button class="btn btn-sm btn-outline-secondary"><i class="bi bi-box-arrow-right me-1"></i>{{ __('admin.sign_out') }}</button></form></div></header>
<div class="container-fluid p-4 p-lg-5">@if(session('success'))<div class="alert alert-success border-0">{{ session('success') }}</div>@endif @if($errors->any())<div class="alert alert-danger border-0"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</div></main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>@stack('scripts')
</body></html>